language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-24.0.1
    - android-24
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-android-leanback
    - extra-google-google_play_services

before_script:
    - chmod +x gradlew
#Build, and run tests
script: "./gradlew build testDebug"
sudo: false
